version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: /
    steps:
      - checkout
      - run:
          name: Run result
          command: |
            pushd ./Tests/UnitTests/
            dotnet test
            popd
